version = 0.1
[default.deploy.parameters]
stack_name = "agentcore-stateless-resources"
resolve_s3 = true
s3_prefix = "agentcore-stateless-resources"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
