version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "python-hello-world-stack"
s3_prefix = "python-hello-world"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "python-hello-world-dev"
s3_prefix = "python-hello-world-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"
confirm_changeset = false
resolve_s3 = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "python-hello-world-prod"
s3_prefix = "python-hello-world-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
confirm_changeset = true
resolve_s3 = true
